### PR TITLE
Add protocols hint

### PR DESCRIPTION
**Pull request by rakaramos**

### CODE REVIEW

**Comment by mmatoszko** [comment]
@rakaramos: why are we adding
> Add "Easy cast with _ObjectiveCBridgeable" hint
twice?

**Comment by mmatoszko** [comment]
@noxytrux @wojteklu @rakaramos It seems great for me. How do yo like it?

**Comment by wojteklu** [comment]
cool, merge and deploy

**Comment by noxytrux** [comment]
I like it!

**Pull request merged**
